language: php

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email: dev@service.viest.me

before_script:
  - git submodule update --init
  - sudo apt-get install zlib1g-dev -y
  - phpize && ./configure && make clean && make

branches:
  only:
    - master
    - dev
script:
    - ./travis/run-test.sh
